//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garuchava_Mazurenko_Bakery.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccount
    {
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public int BasketID { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
