//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garuchava_Mazurenko_Bakery.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int MedBookID { get; set; }
        public int GenderID { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MedBook MedBook { get; set; }
        public virtual MedBook MedBook1 { get; set; }
    }
}
