//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garuchava_Mazurenko_Bakery.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int RecipeID { get; set; }
        public int IngredientID { get; set; }
        public int ProductID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Product Product { get; set; }
    }
}
